--
-- File generated with SQLiteStudio v3.4.4 on Sat Dec 30 17:03:51 2023
--
-- Text encoding used: UTF-8
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: HABIT
DROP TABLE IF EXISTS HABIT;

CREATE TABLE IF NOT EXISTS HABIT (
    HABIT_ID   INTEGER       PRIMARY KEY AUTOINCREMENT,
    NAME       VARCHAR (200),
    START_DATE DATE
);


-- Table: TASK
DROP TABLE IF EXISTS TASK;

CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID     INTEGER      PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR (40),
    PERIODICITY INTEGER,
    STATUS      VARCHAR (20),
    STATUS_DATE DATE,
    HABIT_ID    INT,
    FOREIGN KEY (
        HABIT_ID
    )
    REFERENCES HABIT (HABIT_ID) 
);


-- Table: TASK_HISTORY
DROP TABLE IF EXISTS TASK_HISTORY;

CREATE TABLE IF NOT EXISTS TASK_HISTORY (
    TASK_HISTORY_ID INTEGER      PRIMARY KEY AUTOINCREMENT,
    TASK_ID         INTEGER,
    EVENT_DATE      DATE,
    STATUS_CHANGE   VARCHAR (20),
    FOREIGN KEY (
        TASK_ID
    )
    REFERENCES TASK (TASK_ID) 
);


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
